version: "3.8"

services:
  missions-db:
    image: missions-db
    build: ./missions-db
    container_name: missions-db
    networks:
      - missions-network
    volumes:
      - missions-bdd-data:/var/lib/postgresq/data

  missions-back:
    image: missions-back
    build: ../gestion-des-missions-back/.
    container_name: missions-back
    depends_on:
      - missions-db
    ports:
      - "8081:8080"
    networks:
      - missions-network

  missions-front:
    image: missions-front
    build: .
    container_name: missions-front
    depends_on:
      - missions-back
    ports:
      - "9000:80"
    networks:
      - missions-network

networks:
  missions-network:

volumes:
  missions-bdd-data:
